name: .NET

on:
  push:
    tags:
      - 1.**

env:
  RELEASE_VERSION: ${{ github.ref_name }}
  NUDGET_API_KEY: ${{ secrets.NUDGET_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./src

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
    
    - name: Create package
      run: dotnet pack --output ./ -p:PackageID=SimpleHttpClient -p:PackageVersion=$RELEASE_VERSION
    
    - name: Publish nudget
      run: dotnet nuget push SimpleHttpClient.$RELEASE_VERSION.nupkg --api-key $NUDGET_API_KEY --source https://api.nuget.org/v3/index.json

  
